ElDiario/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import static
from django.conf import settings

urlpatterns = patterns('',
    url(r'^', include('frontend.urls')),
    url(r'^backend', include('admin.urls')),
    url(r'^m/', include('mobile.urls')),
    url(r'^redactor/', include('redactor.urls')),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    url(r'session_security/', include('session_security.urls')),
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ads/urls.py
from django.conf.urls import patterns, url, include

urlpatterns = patterns('',
	url(r'^/$', 'ads.views.home', name='home'),
    url(r'^/nueva/', 'ads.views.add_ad', name='new_add'),
	url(r'^/editar/(?P<id>\d+)/$', 'ads.views.edit_ad', name='edit_ad'),
	url(r'^/publicar/$', 'ads.views.publish_group', name='publish_group'),
	url(r'^/despublicar/$', 'ads.views.unpublish_group', name='unpublish_group'),
	url(r'^/publicar/(?P<id>\d+)/$', 'ads.views.toggle_publish', name='toggle_publish'),
	url(r'^/despublicar/(?P<id>\d+)/$', 'ads.views.toggle_publish', name='toggle_publish'),
	url(r'^/eliminar/$', 'ads.views.delete_ad', name='delete_ad'),
)

session_security/urls.py
"""
One url meant to be used by JavaScript.

session_security_ping
    Connects the PingView.

To install this url, include it in ``urlpatterns`` definition in ``urls.py``,
ie::

    urlpatterns = patterns('',
        # ....
        url(r'session_security/', include('session_security.urls')),
        # ....
    )

"""
try:
    from django.conf.urls import url, patterns
except ImportError:
    from django.conf.urls.defaults import url, patterns

from .views import PingView

urlpatterns = patterns('',
    url(
        'ping/$',
        PingView.as_view(),
        name='session_security_ping',
    ),
)

conf/models.py
from django.db import models

# Create your models here.

content/models.py
#encoding: utf-8
from django.db import models
from django.contrib.auth.models import User
from redactor.fields import RedactorField
from django.template.defaultfilters import slugify
from datetime import datetime as date

MAIN_PAGE_POSITIONS = (
	('S','Secundarias destacado'),
	('A','Otras A'),
	('B','Otras B'),
	('C','Otras C'),
	('D','Otras D'),
	('E','Otras E'),
	('F','Otras F'),
	('G','Otras G'),
	('H','Otras H'),
	('I','Otras I'),
	('J','Otras J'),
	('R','Derecha'),
)

class Category(models.Model):
	slug = models.SlugField(unique=True, blank=True, max_length=150)
	title = models.CharField(max_length=50, verbose_name=u'Título', unique=True)
	description = RedactorField(verbose_name=u'Descripción', blank=True)
	creation_date = models.DateField(auto_now=True)
	author = models.ForeignKey(User, verbose_name=u'Autor')
	published = models.BooleanField(default=True, verbose_name=u'Publicada')
	parent = models.ForeignKey('Category',verbose_name='Padre', related_name='parent_cat', null=True, blank=True)
	main_page_position = models.CharField(
		max_length=1, null=True, blank=True,
		verbose_name=u'Posición en la página de inicio', choices=MAIN_PAGE_POSITIONS
	)

	def __unicode__(self):
		return self.title

	def save(self, *args, **kwargs):
		self.slug = slugify(self.title)
		super(Category, self).save(*args, **kwargs)

class Article(models.Model):
	slug = models.SlugField(unique=True, blank=True)
	title = models.CharField(max_length=100, verbose_name=u'Título', unique=True)
	abstract = RedactorField(verbose_name=u'Resumen')
	content = RedactorField(verbose_name=u'Contenido')
	creation_date = models.DateTimeField(default=date.now)
	author = models.ForeignKey(User, verbose_name=u'Autor')
	category = models.ForeignKey(Category, verbose_name=u'Categoría', null=True, blank=True)
	published = models.BooleanField(default=True, verbose_name=u'Publicado')
	featured = models.BooleanField(default=True, verbose_name="Destacado")
	hits = models.IntegerField(default=0)
	full_width = models.BooleanField(default=False, verbose_name='Ancho completo')
	related_articles = models.ManyToManyField('Article', verbose_name=u'Artículos relacionados', related_name='related', null=True, blank=True)

	def __unicode__(self):
		return self.title

	def save(self, *args, **kwargs):
		self.slug = slugify(self.title)
		super(Article, self).save(*args, **kwargs)

conf/views.py
from django.shortcuts import render_to_response, HttpResponseRedirect, redirect
from django.template import RequestContext
from django.contrib.auth.decorators import login_required

TEMPLATE_DIR = 'conf/../'
# Create your views here.

@login_required(login_url='login')
def home(request):
	if request.method == 'GET':
		settings = load_settings()
		print settings
		return render_to_response(
			TEMPLATE_DIR+'settings.html', 
			{'settings':settings}, 
			context_instance=RequestContext(request)
		)

	if request.method == 'POST':
		data = {}

		for setting in request.POST:
			if not setting == 'csrfmiddlewaretoken':
				data[setting] = request.POST.get(setting)

		save_settings(data)
		
		return HttpResponseRedirect('/backend')



import io, json, os.path
def save_settings(data):
	filepath = os.path.dirname(__file__)
	with io.open(filepath+'/conf.json', 'w', encoding='utf-8') as f:
	  f.write(unicode(json.dumps(data, ensure_ascii=False)))
	  f.close()

def load_settings():
	filepath = os.path.dirname(__file__)
	with io.open(filepath+'/conf.json', 'r', encoding='utf-8') as f:
		content = f.read()
		dumped_data = json.loads(content)
		
		data = []
		for setting in dumped_data:
			data.append((setting, dumped_data[setting]))

	return data

conf/templates/settings.html
{% extends "base.html" %}
{% load static %}
{% load url from future %}
{% block title %} Configuración {% endblock %}

{% block extrastyle %}
		<link rel="stylesheet" href="{% static "css/chosen.min.css"%}"></link>
{% endblock %}

{% block extrahead %}
	<script src="{% static "js/chosen.jquery.min.js"%}"></script>
	<script src="{% static "js/jquery.jeditable.mini.js"%}"></script>
{% endblock %}

{% block breadcrumbs %}
	<ul class="breadcrumb">
		<li><a href="/backend"><i class="fa fa-home"></i> Inicio</a></li>
		<li>
			<i class="fa fa-gears"></i> Configuración
		</li>
	</ul>
{% endblock %}

{% block mainbody %}
	<div id="content-main">
		<div class="row">
			<div class="col-xs-12 col-sm-10 col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
				    	<h2 class="panel-title">
							<i class="fa fa-gears"></i> Configuración
				    	</h2>
				  	</div>
				  	<div class="panel-body">
				  		<div class="row">
				  			<div class="col-xs-12 col-md-6">
				  				<form role="form" action="/backend/configuracion" method="POST">
									{% csrf_token %}

									<div class="panel panel-default">
									  <div class="panel-body">
									  	<h3>Edición Impresa</h3><hr>
											{% for setting, value in settings %}
											    <div class="form-group {% if field.errors %} has-error{% endif %}">
													<div class="input-group">
														<span class="input-group-addon">
															{{setting}}
														</span>
														<input class="form-control" type="text" name="{{setting}}" value="{{ value }}"/>
													</div>
												</div>
											{% endfor %}
											<br>
											<div class="form-group" style="text-align:right;">
												<a href="../backend" class="btn btn-danger">
													Cancelar
												</a>
												<button type="submit" class="btn btn-success">
													Guardar cambios
						    					</button>
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>
				  	</div>
				</div>
			</div>
		</div>
	</div>

	<script type="text/javascript">
		$(document).ready(function(){
			$("#id_related_articles").chosen({placeholder_text_multiple:'Escribe para buscar...',width: "95%"});
		});

		$("body").on("click", ".add_option", function(){
			$(".empty_msg").hide();
			$("#current_options tbody").append(
				"<tr>\
					<td class='opt text-left'>\
						<input type='text' name='options' form='poll_form' class='form-control' placeholder='Ingresa el texto de la opcion'/>\
					</td>\
					<td class='opt text-left'>\
						<button class='add_option btn btn-success'><span class='glyphicon glyphicon-plus'></span></button>\
						<button class='del_option btn btn-danger'><span class='glyphicon glyphicon-remove'></span></button>\
					</td>\
				</tr>"
			);
		});

		$("body").on("click", ".del_option", function(event){
			if($(this).parents("tbody tr").siblings().length===1){
					$(".empty_msg").show();
			}
			$(this).parents("tr").detach();
		});

	</script>
{% endblock %}