ElDiario/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import static
from django.conf import settings

urlpatterns = patterns('',
    url(r'^', include('frontend.urls')),
    url(r'^backend', include('admin.urls')),
    url(r'^m/', include('mobile.urls')),
    url(r'^redactor/', include('redactor.urls')),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    url(r'session_security/', include('session_security.urls')),
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ads/urls.py
from django.conf.urls import patterns, url, include

urlpatterns = patterns('',
	url(r'^/$', 'ads.views.home', name='home'),
    url(r'^/nueva/', 'ads.views.add_ad', name='new_add'),
	url(r'^/editar/(?P<id>\d+)/$', 'ads.views.edit_ad', name='edit_ad'),
	url(r'^/publicar/$', 'ads.views.publish_group', name='publish_group'),
	url(r'^/despublicar/$', 'ads.views.unpublish_group', name='unpublish_group'),
	url(r'^/publicar/(?P<id>\d+)/$', 'ads.views.toggle_publish', name='toggle_publish'),
	url(r'^/despublicar/(?P<id>\d+)/$', 'ads.views.toggle_publish', name='toggle_publish'),
	url(r'^/eliminar/$', 'ads.views.delete_ad', name='delete_ad'),
)

session_security/urls.py
"""
One url meant to be used by JavaScript.

session_security_ping
    Connects the PingView.

To install this url, include it in ``urlpatterns`` definition in ``urls.py``,
ie::

    urlpatterns = patterns('',
        # ....
        url(r'session_security/', include('session_security.urls')),
        # ....
    )

"""
try:
    from django.conf.urls import url, patterns
except ImportError:
    from django.conf.urls.defaults import url, patterns

from .views import PingView

urlpatterns = patterns('',
    url(
        'ping/$',
        PingView.as_view(),
        name='session_security_ping',
    ),
)

suscriptions/urls.py
from django.conf.urls import patterns, url, include

urlpatterns = patterns('',
	url(r'^/$', 'suscriptions.views.list_suscriptions', name='suscriptions'),
    url(r'^/nueva/', 'suscriptions.views.add_suscription', name='new_suscription'),
    url(r'^/editar/(?P<id>\d+)/$', 'suscriptions.views.edit_suscription', name='edit_suscription'),
    url(r'^/activar/$', 'suscriptions.views.activate_group', name='activate_group'),
    url(r'^/desactivar/$', 'suscriptions.views.deactivate_group', name='deactivate_group'),
    url(r'^/activar/(?P<id>\d+)/$', 'suscriptions.views.toggle_publish', name='toggle_publish'),
    url(r'^/desactivar/(?P<id>\d+)/$', 'suscriptions.views.toggle_publish', name='toggle_publish'),
    url(r'^/eliminar/$', 'suscriptions.views.delete_suscription', name='delete_category'),
)

ads/models.py
#encoding: utf-8
from django.db import models
from django.template.defaultfilters import slugify
from django.conf import settings

from content.models import Category

# Create your models here.

import os
import zipfile
import shutil

class Ad(models.Model):

	POSITION_INDEXES = (
		('1','1: Pre Encabezado (1080x160)'),
		('2','2: Externa Izquierda (134x660)'),
		('3','3: Externa Derecha (134x660)'),
		('4','4: Post Encabezado 1080x90'),
		('5','5: Pre Principales (710x120)'),
		('6','6: Post Principales (710x160)'),
		('7','7: Derecha Arriba A (275x300)'),
		('8','8: Derecha Arriba B (275x90)'),
		('9','9: Derecha Abajo (275x300)'),
		('10','10: Post Twitter (275 de ancho)'),
		('11','11: Móvil'),
	)

	AD_TYPES = (
		('1', 'Animación'),
		('2', 'Imagen'),
		('3', 'Video/HTML'),
	)

	title = models.CharField(verbose_name=u'Título', max_length=100, unique=True)
	ad_type = models.CharField(verbose_name=u'Tipo', choices=AD_TYPES, max_length=10)
	ad_file = models.FileField(verbose_name=u'Archivo', upload_to='uploads/ads/zipped', default='No File')
	embed_code = models.TextField(verbose_name=u'Código HTML', default='Insertar HTML', blank=True)
	position = models.CharField(verbose_name=u'Posición', choices=POSITION_INDEXES, max_length=30)
	creation_date = models.DateField(auto_now=True)
	published = models.BooleanField(default=True, verbose_name=u'Publicado')
	categories = models.ManyToManyField(Category, verbose_name='Categorías relacionadas')

	def save(self, *args, **kwargs):
		if not self.id:
			super(Ad, self).save(*args, **kwargs)
		
		if not (self.position == "10" or self.position == "11"):
			Ad.objects.filter(
				position=self.position
			).exclude(id=self.id).update(published=False)
		
		super(Ad, self).save(*args, **kwargs)

suscriptions/models.py
#encoding: utf-8

from django.db import models

# Create your models here.

class Suscription(models.Model):

	first_name = models.CharField(verbose_name=u'Nombres', max_length=50)
	last_name = models.CharField(verbose_name=u'Apellidos', max_length=50)
	dni = models.CharField(unique=True, verbose_name=u'Documento de Identidad', max_length=15)
	phone = models.CharField(verbose_name=u'Teléfono', max_length=10, blank=True, null=True)
	mobile = models.CharField(verbose_name=u'Teléfono móvil', max_length=13)
	email = models.EmailField(verbose_name=u'Correo Electrónico')
	address = models.CharField(verbose_name=u'Dirección', max_length=50)
	city = models.CharField(verbose_name=u'Ciudad', max_length=30)
	suscription_date = models.DateField(verbose_name=u'Fecha de suscripción', blank=True, null=True)
	suscription_end_date = models.DateField(verbose_name=u'Fin de la suscripción', blank=True, null=True)
	status = models.BooleanField(verbose_name=u'Suscripción activa', default=False)

suscriptions/forms.py
from models import *
from django import forms

class SuscriptionForm(forms.ModelForm):

	class Meta:
		model = Suscription

suscriptions/views.py
# Create your views here.
#encoding: utf-8
from django.shortcuts import render_to_response, HttpResponseRedirect, redirect
from django.template import RequestContext
from models import *
from forms import *
from django.contrib.auth.decorators import permission_required, login_required
from content.models import Category
# Create your views here.

TEMPLATE_DIR = 'suscriptions/../'

@login_required(login_url='login')
def list_suscriptions(request):
	suscriptions = Suscription.objects.all()

	return render_to_response(TEMPLATE_DIR+'susc_index.html', {'suscribed_list':suscriptions},
							   context_instance=RequestContext(request))


@login_required(login_url='login')
@permission_required('suscriptions.add_suscription', login_url='/backend/permisos_insuficientes/')
def add_suscription(request):

	if request.method == 'GET':
		form = SuscriptionForm()
		return render_to_response(TEMPLATE_DIR+'add_edit_susc.html',
							  {'form':form}, context_instance=RequestContext(request))

	elif request.method == 'POST':
		form = SuscriptionForm(request.POST)
        if form.is_valid():
            new_suscription = form.save()
            return HttpResponseRedirect('/backend/suscripciones')
        else:
        	return render_to_response(TEMPLATE_DIR+'add_edit_susc.html',
							  {'form':form}, context_instance=RequestContext(request))

@login_required(login_url='login')
@permission_required('suscriptions.edit_suscription', login_url='/backend/permisos_insuficientes/')
def edit_suscription(request, id):

	suscription = Suscription.objects.get(id=id)
	full_name = suscription.first_name+' '+suscription.last_name
	if request.method == 'GET':
		form = SuscriptionForm(instance=suscription)
		return render_to_response(TEMPLATE_DIR+'add_edit_susc.html',
							  {'form':form, 'editing': True, 'title': full_name}, context_instance=RequestContext(request))

	elif request.method == 'POST':
		form = SuscriptionForm(request.POST, instance=suscription)
        if form.is_valid():
            new_suscription = form.save()
            return HttpResponseRedirect('/backend/suscripciones')
        else:
        	return render_to_response(TEMPLATE_DIR+'add_edit_susc.html',
							  {'form':form, 'editing': True, 'title': full_name}, context_instance=RequestContext(request))

@login_required(login_url='login')
@permission_required('suscriptions.edit_suscription', login_url='/backend/permisos_insuficientes/')
def activate_group(request):

	ids = request.POST.getlist('id')

	for id in ids:
		suscription = Suscription.objects.get(id=id)
		suscription.status = True
		suscription.save()

	return HttpResponseRedirect('/backend/suscripciones')

@login_required(login_url='login')
@permission_required('suscriptions.edit_suscription', login_url='/backend/permisos_insuficientes/')
def deactivate_group(request):

	ids = request.POST.getlist('id')

	for id in ids:
		suscription = Suscription.objects.get(id=id)
		suscription.status = False
		suscription.save()

	return HttpResponseRedirect('/backend/suscripciones')

@login_required(login_url='login')
@permission_required('suscriptions.edit_suscription', login_url='/backend/permisos_insuficientes/')
def toggle_publish(request, id):

	suscription = Suscription.objects.get(id=id)
	suscription.status = not suscription.status
	suscription.save()
	return HttpResponseRedirect('/backend/suscripciones')


@login_required(login_url='login')
@permission_required('suscriptions.delete_suscription', login_url='/backend/permisos_insuficientes/')
def delete_suscription(request):

	ids = request.POST.getlist('id')

	for id in ids:
		suscription = Suscription.objects.get(id=id)
		suscription.delete()

	return HttpResponseRedirect('/backend/suscripciones')

def frontend_suscription(request):

	if request.method == 'GET':
		form = SuscriptionForm()
		categories = Category.objects.filter(parent=None)
		return render_to_response('frontend/../add_susc.html',
								{'form':form, 'categories': categories}, context_instance=RequestContext(request))

	elif request.method == 'POST':
		form = SuscriptionForm(request.POST)
		if form.is_valid():
			new_suscription = form.save()
			return render_to_response('frontend/../add_susc.html',
									{'done':True}, context_instance=RequestContext(request))
		else:
			return render_to_response('frontend/../add_susc.html',
			{'form':form}, context_instance=RequestContext(request))

suscriptions/templates/add_edit_susc.html
{% extends "base.html" %}
{% load static %}
{% load url from future %}
{% block title %} {% if editing %} Editando la suscripción: {{title}} {% else %} Nueva suscripción {% endif %} {% endblock %}

{% block extrastyle %}
		<link rel="stylesheet" href="{% static "css/chosen.min.css"%}"></link>
{% endblock %}

{% block extrahead %}
	<script src="{% static "js/chosen.jquery.min.js"%}"></script>
	<script src="{% static "js/chosen.jquery.min.js"%}"></script>
{% endblock %}

{% block breadcrumbs %}
	<ul class="breadcrumb">
		<li><a href="/backend"><i class="fa fa-home"></i> Inicio</a></li>
		<li><a href="/backend/suscripciones"><i class="fa fa-bullhorn"></i> Suscripciones</a></li>
		<li>
			<i class="{% if editing %}fa fa-edit {% else %}fa fa-plus {% endif %}"></i>
			{% if editing %} Editar Suscripción ({{title}}) {% else %} Nueva Suscripción {% endif %}
		</li>
	</ul>
{% endblock %}

{% block mainbody %}
	<div id="content-main">
		<div class="row">
			<div class="col-xs-12 col-sm-10 col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
				    	<h2 class="panel-title">
				    		{% if editing %} <span class="fa fa-edit"></span> Editar Suscripción ({{title}})
				    		{% else %} <span class="fa fa-plus"></span> Nueva Suscripción  {% endif %}

				    	</h2>
				  	</div>
				  	<div class="panel-body">
				  		<div class="row">
				  			<div class="col-md-1"></div>
				  			<div class="col-xs-12 col-md-10">

									<div class="susc-tab">
										<span>DEPARTAMENTO</span> Últimas Noticias
									</div>

				  				<form role="form" action="." method="POST" enctype="multipart/form-data">
									{% csrf_token %}

									<input type="hidden" name="user_id" value="{{user}}" />

									{% for field in form %}
										{% if field.name == "embed_code"%}
										<div class="form-group {% if field.errors %} has-error{% endif %}" style="display:none;">
										{% else %}
										<div class="form-group {% if field.errors %} has-error{% endif %}">
										{% endif %}
											{% if not form.this_is_the_login_form.errors %}
											<label class="control-label required" for="{{field.field.id}}">
												{{field.label}}:
											</label>
											{% endif %}

											{% if field.errors %}
												<span class="help-inline text-danger">
													{{field.errors}}
												</span>
											{% endif %}

											<div class="input-group">
												<span class="input-group-addon">
													<span class="glyphicon glyphicon-asterisk"></span>
												</span>
												{{ field }}
											</div>




										</div>
									{% endfor %}

									<br><br>
									<div class="form-group" style="text-align:right;">
										<a href="{% if editing %}../../{% else %}../{% endif %}" class="btn btn-danger">
											Cancelar
										</a>
										<button type="submit" class="btn btn-success">
											{% if editing %} Guardar cambios
				    						{% else %} Crear Suscripción {% endif %}
				    					</button>
									</div>
								</form>
				  			</div>
				  		</div>
				  	</div>
				</div>
			</div>
		</div>
	</div>

	<style type="text/css">
		#id_ad_type li{
			list-style: none; display: inline-block; margin-right: 20px;
		}

		#id_ad_type li label{
			line-height: 42px;
		}

		#id_ad_type li .form-control{
			display: inline; margin-right: 5px; width: auto;
		}
	</style>

	<script type="text/javascript">
		$(document).ready(function(){
			$("#id_ad_type li:first").detach()

			{% if not editing %}
			$("#id_ad_type :radio:first").attr("checked", "checked");
			{% endif %}
			//alert($("input[name=ad_type][value=1]").("color"))
			$("#id_ad_type").siblings(".input-group-addon").detach()

			$("#id_ad_type :radio").change(function(){
				if($(this).val()==3){
					$("#id_pkg_file").parents(".form-group").fadeOut(function(){
						$("#id_embed_code").parents(".form-group").slideDown();
					});

				}else{
					$("#id_embed_code").parents(".form-group").slideUp(function(){
						$("#id_pkg_file").parents(".form-group").fadeIn();
					});
				}
			})


		});
	</script>
{% endblock %}

suscriptions/templates/susc_index.html
{% extends "base.html" %}
{% load url from future %}
{% block title %} Administrar Suscripciones {% endblock %}

{% block breadcrumbs %}
	<ul class="breadcrumb">
		<li><a href="/backend"><i class="fa fa-home"></i> Inicio</a></li>
		<li class="active"><i class="fa fa-send"></i> Suscripciones</li>
	</ul>
{% endblock %}

{% block mainbody %}
	<div id="content-main">
		<div class="row">
			<div class="col-xs-12 col-sm-10 col-md-12">
				<div class="panel panel-default">
				  <div class="panel-heading">
				    <h2 class="panel-title" style="display:inline-block; margin-right:5px">
				    	<span class="fa fa-send"></span> Suscripciones
				    </h2>
				    <div class="hidden-xs" style="display:inline-block;width:50%;"></div>
				    <div class="btn-group" style="display:inline-block;">
						<a href="nueva/" class="btn btn-success">
							<span class="fa fa-plus"></span> <span class="hidden-xs"> Nueva Suscripción</span>
						</a>
						<a href="activar/" class="btn btn-primary toggle_publish disabled">
							<span class="glyphicon glyphicon-ok"></span> <span class="hidden-xs">Activar</span>
						</a>
						<a href="desactivar/" class="btn btn-warning toggle_publish disabled">
							<span class="glyphicon glyphicon-remove"></span> <span class="hidden-xs">Desactivar</span>
						</a>
						<a href="eliminar/" class="btn btn-danger delete disabled">
							<span class="glyphicon glyphicon-fire"></span> <span class="hidden-xs">Eliminar</span>
						</a>
					</div>
				  </div>
				  <div class="panel-body" style="padding:0">

				  	<form id="all_objects" method="POST">{% csrf_token %}</form>

				    <table class="table table-striped">
				      <thead>
				        <tr class="active">
				        	<th><input type="checkbox" id="toggle_all"/></th>
				        	<th class="text-center hidden-xs">ID</th>
				        	<th class="text-left">Nombre</th>
				        	<th class="text-center">DNI</th>
				        	<th class="text-center hidden-xs">Móvil</th>
				        	<th class="text-center">Teléfono</th>
				        	<th class="text-center">Email</th>
				        	<th class="text-center">Dirección</th>
				        	<th class="text-center">Ciudad</th>
				        	<th class="text-center">Activa</th>
				        	<th class="text-center hidden-xs">Fecha de suscripción</th>
				        	<th class="text-center hidden-xs">Fin de suscripción</th>
				        </tr>
				      </thead>
				      <tbody>
				      	{% for suscription in suscribed_list%}
				        <tr>
				        	<td class="text-left;">
				        		<input type="checkbox" class="check" name="id" form="all_objects" value="{{suscription.id}}"/>
				        	</td>
				        	<td class="text-center hidden-xs">{{suscription.id}}</td>
				        	<td class="text-left">
				        		<a href="editar/{{suscription.id}}">
				        			{{suscription.first_name}} {{suscription.last_name}}
				        		</a>
				        	</td>
				        	<td class="text-center hidden-xs">{{suscription.dni}}</td>
				        	<td class="text-center hidden-xs">{{suscription.mobile}}</td>
				        	<td class="text-center hidden-xs">
				        		{% if suscription.phone %}{{suscription.phone}}{% else %}---{%endif%}
				        	</td>
				        	<td class="text-center hidden-xs">{{suscription.email}}</td>
							<td class="text-center hidden-xs">{{suscription.address}}</td>
							<td class="text-center hidden-xs">{{suscription.city}}</td>

				        	<td class="text-center hidden-xs">

				        		{% if suscription.status %}
				        		<a href="desactivar/{{suscription.id}}">
				        			<span class="glyphicon glyphicon-ok text-primary"></span>
				        		</a>
				        		{% else %}
				        		<a href="activar/{{suscription.id}}">
				        			<span class="glyphicon glyphicon-remove"></span>
				        		</a>
				        		{% endif %}
				        	</td>

				        	<td class="text-center hidden-xs">
										{% if suscription.suscription_date %}{{suscription.suscription_date}}{% else %}---{%endif%}
									</td>
				        	<td class="text-center hidden-xs">
										{% if suscription.suscription_end_date %}{{suscription.suscription_end_date}}{% else %}---{%endif%}
									</td>
				        </tr>
				        {% empty %}
				        <tr>
				        	<td colspan="12" class="text-center">
				        		<div class="alert alert-info">No has creado suscripciones
				        			<br><br>
				        			<b>
				        				<a href="nueva/">
				        					<span class="fa fa-plus"></span> Crear Suscripción
				        				</a>
				        			</b>
				        		</div>
				        	</td>
				        </tr>
				        {% endfor %}
				      </tbody>
				    </table>
				  </div>
				</div>
			</div>
		</div>
	</div>

	<script type="text/javascript">
	$(".delete").confirm({
		text: "Vas a eliminar una o más publicidades, esta acción no se puede deshacer. ¿Aún deseas continuar?",
	    title: "Procede con cuidado!",
	    confirm: function(button) {
	        $("#all_objects").attr("action", button.attr("href"));
			$("#all_objects").submit();
	    },
	    cancel: function(button) {
	        return false;
	    },
	    confirmButton: "Lo entiendo, deseo continuar",
	    cancelButton: "No",
	    post: false
	});
	</script>


{% endblock %}