ElDiario/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import static
from django.conf import settings

urlpatterns = patterns('',
    url(r'^', include('frontend.urls')),
    url(r'^backend', include('admin.urls')),
    url(r'^m/', include('mobile.urls')),
    url(r'^redactor/', include('redactor.urls')),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    url(r'session_security/', include('session_security.urls')),
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ads/urls.py
from django.conf.urls import patterns, url, include

urlpatterns = patterns('',
	url(r'^/$', 'ads.views.home', name='home'),
    url(r'^/nueva/', 'ads.views.add_ad', name='new_add'),
	url(r'^/editar/(?P<id>\d+)/$', 'ads.views.edit_ad', name='edit_ad'),
	url(r'^/publicar/$', 'ads.views.publish_group', name='publish_group'),
	url(r'^/despublicar/$', 'ads.views.unpublish_group', name='unpublish_group'),
	url(r'^/publicar/(?P<id>\d+)/$', 'ads.views.toggle_publish', name='toggle_publish'),
	url(r'^/despublicar/(?P<id>\d+)/$', 'ads.views.toggle_publish', name='toggle_publish'),
	url(r'^/eliminar/$', 'ads.views.delete_ad', name='delete_ad'),
)

session_security/urls.py
"""
One url meant to be used by JavaScript.

session_security_ping
    Connects the PingView.

To install this url, include it in ``urlpatterns`` definition in ``urls.py``,
ie::

    urlpatterns = patterns('',
        # ....
        url(r'session_security/', include('session_security.urls')),
        # ....
    )

"""
try:
    from django.conf.urls import url, patterns
except ImportError:
    from django.conf.urls.defaults import url, patterns

from .views import PingView

urlpatterns = patterns('',
    url(
        'ping/$',
        PingView.as_view(),
        name='session_security_ping',
    ),
)

ads/models.py
#encoding: utf-8
from django.db import models
from django.template.defaultfilters import slugify
from django.conf import settings

from content.models import Category

# Create your models here.

import os
import zipfile
import shutil

class Ad(models.Model):

	POSITION_INDEXES = (
		('1','1: Pre Encabezado (1080x160)'),
		('2','2: Externa Izquierda (134x660)'),
		('3','3: Externa Derecha (134x660)'),
		('4','4: Post Encabezado 1080x90'),
		('5','5: Pre Principales (710x120)'),
		('6','6: Post Principales (710x160)'),
		('7','7: Derecha Arriba A (275x300)'),
		('8','8: Derecha Arriba B (275x90)'),
		('9','9: Derecha Abajo (275x300)'),
		('10','10: Post Twitter (275 de ancho)'),
		('11','11: Móvil'),
	)

	AD_TYPES = (
		('1', 'Animación'),
		('2', 'Imagen'),
		('3', 'Video/HTML'),
	)

	title = models.CharField(verbose_name=u'Título', max_length=100, unique=True)
	ad_type = models.CharField(verbose_name=u'Tipo', choices=AD_TYPES, max_length=10)
	ad_file = models.FileField(verbose_name=u'Archivo', upload_to='uploads/ads/zipped', default='No File')
	embed_code = models.TextField(verbose_name=u'Código HTML', default='Insertar HTML', blank=True)
	position = models.CharField(verbose_name=u'Posición', choices=POSITION_INDEXES, max_length=30)
	creation_date = models.DateField(auto_now=True)
	published = models.BooleanField(default=True, verbose_name=u'Publicado')
	categories = models.ManyToManyField(Category, verbose_name='Categorías relacionadas')

	def save(self, *args, **kwargs):
		if not self.id:
			super(Ad, self).save(*args, **kwargs)
		
		if not (self.position == "10" or self.position == "11"):
			Ad.objects.filter(
				position=self.position
			).exclude(id=self.id).update(published=False)
		
		super(Ad, self).save(*args, **kwargs)

admin/templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>

<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--><!--<![endif]-->

<html lang="{{ LANGUAGE_CODE|default:"es-co" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
	<head>
		<meta charset="utf-8">
		<title>{% block title %}Periódico El Diario - Administración{% endblock %}</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="description" content="Administración del sitio web de El Diario">
        <meta name="viewport" content="width=device-width, initial-scale=1">

		<link rel="icon" type="image/png" href="{% static "images/favicon.png" %}">

		<link rel="stylesheet" href="{% static "css/bootstrap.css" %}" />
		<link rel="stylesheet" href="{% static "css/bootstrap-theme.min.css" %}">
        <link rel="stylesheet" href="{% static "css/main.css" %}">
        <link rel="stylesheet" href="{% static "redactor/css/redactor.css" %}">
        <link rel="stylesheet" href="{% static "css/bootstrap-datetimepicker.min.css" %}">

        <link href="//fonts.googleapis.com/css?family=Open+Sans:300italic,300,400italic,400,600italic,600,700italic,700,800italic,800" rel="stylesheet" type="text/css">

        <style>

            body, html{
                height: 100%;
                padding: 0;
                margin: 0;
                width: 100%;
                overflow-x: hidden;
            }
            body{
            	margin-top: 50px;
            	height: calc( 100% - 50px );
            }
        </style>

		<script src="{% static "js/jquery.js" %}"></script>
		{% include "session_security/all.html" %}
		<script src="{% static "js/bootstrap.min.js" %}"></script>
		<script src="{% static "js/moment.min.js" %}"></script>
		<script src="{% static "redactor/redactor.js" %}"></script>
		<script src="{% static "redactor/jquery-migrate.min.js" %}"></script>
		<script src="{% static "js/bootstrap-datetimepicker.min.js" %}"></script>
		<script src="{% static "js/jquery.confirm.min.js" %}"></script>

		{% block extrastyle %}{% endblock %}
		{% block extrahead %}{% endblock %}
		{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
	</head>

	<body>
		{% block topmenu %}
			{% include "topmenu.html" %}
		{% endblock %}

		<div class="container-fluid" style="padding-top: 25px">

		{% block breadcrumbs %}
		{% endblock %}

		{% block mainbody %}

		{% endblock %}
		</div>

		{% block footer %}{% endblock %}
		<script type="text/javascript">

			$(document).ready(function(){

				$(":checkbox").siblings(".input-group-addon").remove();

				$("textarea").siblings(".input-group-addon").remove();

				$("#id_creation_date, #id_suscription_date, #id_suscription_end_date, #id_capture_datetime").siblings('.input-group-addon, input').detach();

				$("#id_creation_date, #id_suscription_date, #id_suscription_end_date, #id_capture_datetime").after(
					'<span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>'
				);

				$("#id_creation_date, #id_capture_datetime")
					.parents('.input-group').addClass('date').attr('data-date-format', 'DD/MM/YYYY hh:mm:ss');

				$("#id_suscription_date, #id_suscription_end_date")
					.parents('.input-group').addClass('date').attr('data-date-format', 'DD/MM/YYYY');

				$("#id_creation_date, #id_capture_datetime")
					.parents('.input-group').datetimepicker({pickTime:true, language: 'es'});

				$("#id_suscription_date, #id_suscription_end_date")
					.parents('.input-group').datetimepicker({pickTime:false, language: 'es'});


				$("input, textarea").addClass("form-control");

				$("#uploadForm textarea").attr("rows", 3)
				$(".panel-body .form-group input:first").focus();
				$(".input-group select, input[type=file]").siblings(".input-group-addon").remove();


				$(":checkbox").parents('.form-group').css({"max-width":"15%", "display": "inline-block", "padding": "20px"});

				$(".input-group select").css("width", "100%").parent().css("width", "100%");

				$(".add-another").addClass("btn btn-default").html('<span class="glyphicon glyphicon-plus"></span>');

				$('#toggle_all').click(function(event) {
			        if(this.checked) {
			        	$(".toggle_publish, .toggle_feature, .delete").removeClass('disabled');
			            $('.check').each(function() {
			                this.checked = true;
			            });
			        }else{
			        	$(".toggle_publish, .toggle_feature, .delete").addClass('disabled');
			            $('.check').each(function() {
			                this.checked = false;
			            });
			        }
			    });

			    $(".check").change(function(){
			    	if($(".check:checked").length>0){
			    		$(".toggle_publish, .toggle_feature, .delete").removeClass('disabled');
			    	}else{
			    		$(".toggle_publish, .toggle_feature, .delete").addClass('disabled');
			    	}

			    	if($(".check").length===$(".check:checked").length){
			    		$("#toggle_all").attr("checked", true);
			    	}else{
			    		$("#toggle_all").attr("checked", false);
			    	}
			    });

			    $(".toggle_publish, .toggle_feature").click(function(event){
			    	event.preventDefault();
			    	$("#all_objects").attr("action", $(this).attr("href"));
			    	$("#all_objects").submit();
			    });
			});
		</script>
	</body>
</html>

admin/templates/index.html
{% extends "base.html" %}
{% load static %}
{% load url from future %}

{% block extrahead %}
	<script>
		(function(w,d,s,g,js,fs){
		  g=w.gapi||(w.gapi={});g.analytics={q:[],ready:function(f){this.q.push(f);}};
		  js=d.createElement(s);fs=d.getElementsByTagName(s)[0];
		  js.src='https://apis.google.com/js/platform.js';
		  fs.parentNode.insertBefore(js,fs);js.onload=function(){g.load('analytics');};
		}(window,document,'script'));
	</script>
{% endblock %}

{% block breadcrumbs %}
	<ul class="breadcrumb">
		<li class="active"><i class="fa fa-home"></i> Inicio</li>
	</ul>
{% endblock %}

{% block mainbody %}
	<div id="content-main">
		<div class="row">
			<div class="col-xs-12 col-sm-10 col-md-9">
				<!--Analytics Panel-->
				<div class="panel-group" id="analytics">
				  <div class="panel panel-default">
				    <div class="panel-heading">
				      <h4 class="panel-title">
				        <a data-toggle="collapse" data-parent="#analytics" href="#collapseOne">
				          <span class="glyphicon glyphicon-stats"></span>
				          Estadísticas de visitantes (Google Analytics)
				        </a>
				      </h4>
				    </div>
				    <div id="collapseOne" class="panel-collapse collapse">
				      <div class="panel-body">

							<div class="row-fluid hidden-phone">
								<div id="embed-api-auth-container">
									
								</div>
								<div id="chart-container">
									
								</div>
								<div id="view-selector-container">
									
								</div>
							</div>
				      </div>
				    </div>
				  </div>
				</div>

				<!--Apps panel-->
				<div class="panel-group" id="apps">
				  <div class="panel panel-default">
				    <div class="panel-heading">
				      <h4 class="panel-title">
				        <a data-toggle="collapse" data-parent="#apps" href="#collapseTwo">
				          <span class="glyphicon glyphicon-th-large"></span>
				          Aplicaciones
				        </a>
				      </h4>
				    </div>
				    <div id="collapseTwo" class="panel-collapse collapse in">
				      <div class="panel-body">
				        <!--div class="app_link col-xs-5 col-sm-3 col-md-2">
							<a href="pagina_principal" class="section app_link_content">
								<span class="fa fa-star"></span>
								<b>Página principal</b>
							</a>
						</div-->
						<div class="app_link col-xs-5 col-sm-3 col-md-2">
							<a href="contenido/categorias" class="section app_link_content">
								<span class="fa fa-inbox"></span>
								<b>Categorías</b>
							</a>
						</div>
						<div class="app_link col-xs-5 col-sm-3 col-md-2">
							<a href="contenido/articulos" class="section app_link_content">
								<span class="glyphicon glyphicon-leaf"></span>
								<b>Artículos</b>
							</a>
						</div>
						<div class="app_link col-xs-5 col-sm-3 col-md-2">
							<a href="fotogalerias" class="section app_link_content">
								<span class="fa fa-camera"></span>
								<b>Fotogalerías</b>
							</a>
						</div>
						<div class="app_link col-xs-5 col-sm-3 col-md-2">
							<a href="vive_boyaca" class="section app_link_content">
								<span class="fa fa-road"></span>
								<b>Vive Boyacá</b>
							</a>
						</div>
						<div class="app_link col-xs-5 col-sm-3 col-md-2">
							<a href="publicidad" class="section app_link_content">
								<span class="fa fa-bullhorn"></span>
								<b>Publicidad</b>
							</a>
						</div>
						<div class="app_link col-xs-5 col-sm-3 col-md-2">
							<a href="acceso" class="section app_link_content">
								<span class="fa fa-lock"></span>
								<b>Acesso</b>
							</a>
						</div>
						<div class="app_link col-xs-5 col-sm-3 col-md-2">
							<a href="encuestas" class="section app_link_content">
								<span class="fa fa-tasks"></span>
								<b>Encuestas</b>
							</a>
						</div>
						<div class="app_link col-xs-5 col-sm-3 col-md-2">
							<a href="suscripciones" class="section app_link_content">
								<span class="fa fa-send"></span>
								<b>Suscripciones</b>
							</a>
						</div>
						<div class="app_link col-xs-5 col-sm-3 col-md-2">
							<a href="configuracion" class="section app_link_content">
								<span class="fa fa-gears"></span>
								<b>Configuración</b>
							</a>
						</div>
						<!--div class="app_link col-xs-5 col-sm-3 col-md-2">
							<a href="plugins" class="section app_link_content">
								<span class="fa fa-sliders"></span>
								<b>Plugins</b>
							</a>
						</div-->
				      </div>
				    </div>
				  </div>
				</div>
		  	</div>

		  	<div class="col-xs-12 col-sm-2 col-md-3">
				<div class="well well-open">
					<h3 class="filter-title">Acciones recientes</h3>
					<ul class="nav nav-list">

						{% if not admin_log %}
							<li>
								<p class="tip">No se han registrado acciones</p>
							</li>
						{% else %}
							{% for entry in admin_log %}
							<li>
								{% if not entry.is_deletion and entry.get_admin_url %}
								<a class="log-link" href="{{ entry.get_admin_url }}">
								{% endif %}
									<i class="glyphicon glyphicon-{% if entry.is_addition %}plus{% elif entry.is_change %}edit{% elif entry.is_deletion %}remove{% endif %}"></i>

									{{ entry.object_repr }}

								{% if not entry.is_deletion and entry.get_admin_url %}
								</a>
								{% endif %}

								{% if entry.content_type %}
								<span class="mini quiet">
									{% filter capfirst %}entry.content_type.name{% endfilter %}
								</span>
								{% else %}
								<span class="mini quiet">Unknown content</span>
								{% endif %}
								<span class="mini">{{entry.action_time|date:"d N, H:i"}}</span>
							</li>
							{% endfor %}
						{% endif %}
					</ul>
				</div>
		  	</div>
		</div>
	</div>
	<script>
		gapi.analytics.ready(function() {

		  /**
		   * Authorize the user immediately if the user has already granted access.
		   * If no access has been created, render an authorize button inside the
		   * element with the ID "embed-api-auth-container".
		   */
		  gapi.analytics.auth.authorize({
		    container: 'embed-api-auth-container',
		    clientid: '1040359910878-qsqk1n60bfs89rg14sg8i21gerglh63m.apps.googleusercontent.com',
		  });


		  /**
		   * Create a new ViewSelector instance to be rendered inside of an
		   * element with the id "view-selector-container".
		   */
		  var viewSelector = new gapi.analytics.ViewSelector({
		    container: 'view-selector-container'
		  });

		  // Render the view selector to the page.
		  viewSelector.execute();


		  /**
		   * Create a new DataChart instance with the given query parameters
		   * and Google chart options. It will be rendered inside an element
		   * with the id "chart-container".
		   */
		  var dataChart = new gapi.analytics.googleCharts.DataChart({
		    query: {
		      metrics: ['ga:users','ga:newUsers'],
		      dimensions: 'ga:date',
		      'start-date': '2014-06-01',
		      'end-date': 'yesterday'
		    },
		    chart: {
		      container: 'chart-container',
		      type: 'LINE',
		      options: {
		        width: '100%'
		      }
		    }
		  });


		  /**
		   * Render the dataChart on the page whenever a new view is selected.
		   */
		  viewSelector.on('change', function(ids) {
		    dataChart.set({query: {ids: ids}}).execute();
		  });

		});
	</script>
{% endblock %}

admin/templates/login.html
{% extends "base.html" %}
{% load i18n %}

{% block topmenu %}{% endblock %}

{% block mainbody %}

	<div class="jumbotron" style="height:100%; margin-bottom:0; position:absolute; top:0; bottom:0; left:0;width:100%">
    	<div class="row">
    		<div class="col-xs-1 col-sm-2 col-md-2"></div>
    		<div class="col-xs-10 col-sm-8 col-md-8">
    			<div style="text-align:center">
    				<img alt="imagen no disponible" src="https://fbcdn-sphotos-f-a.akamaihd.net/hphotos-ak-ash3/t1.0-9/734113_389386964485689_331498768_n.jpg" 
		    			 alt="Periódico El Diario" class="img-rounded" width="100">
					<h1>Periódico El Diario</h1>
					<p>Administrador web</p>
		      		<h5>Inicia sesión para continuar</h5>
    			</div>
    			
	      		<br>	
	      		<div class="row">
	      			<div class="col-xs-0 col-sm-1 col-md-2"></div>
					<div class="col-xs-12 col-sm-10 col-md-8">
					{% if form_err.errors %}
						{% if not form_err.error%}
						<div class="alert alert-danger alert-dismissable">
							<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
							{% blocktrans count form.errors.items|length as counter %}
								Por favor corrije el siguiente error:
								{% plural %}Por favor corrije los siguientes errores:
							{% endblocktrans %}
						</div>
						{% endif %}
					{% endif %}

					{% if form_err.error %}
					<div class="alert alert-danger alert-dismissable">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						{{form_err.error}}
					</div>
					{% endif %}
					
					<form role="form" action="login" method="POST">
						{% csrf_token %}
						<input type="hidden" name="this_is_the_login_form" value="1" />

						<div class="form-group {% if form_err.username_errors %} has-error{% endif %}">
							{% if not form.this_is_the_login_form.errors %}
							<label class="control-label required" for="id_username">Usuario:</label>
							{% endif %}

							{% if form_err.username_errors %}
								<span class="help-inline text-danger">
									{{form_err.username_errors}}
								</span>
							{% endif %}

							<div class="input-group">
								<span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
								{{ form.username }}
							</div>
						</div>

						<div class="form-group {% if form_err.password_errors %} has-error{% endif %}">
							{% if not form.this_is_the_login_form.errors %}
							<label class="control-label required" for="id_password">Contraseña:</label>
							{% endif %}

							{% if form_err.password_errors %}
								<span class="help-inline text-danger">
									{{form_err.password_errors}}
								</span>
							{% endif %}

							<div class="input-group">
								<span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
								{{ form.password }}
							</div>
						</div>

						<div class="form-group" style="text-align:right;">
							<a href="recuperar_password">Olvidé mi contraseña</a>

							<button type="submit" class="btn btn-success" style="margin-left:20px">Iniciar Sesión</button>
						</div>				
					</form>
					</div>
				</div>
    		</div>
    		
      	</div>
    </div>

	<script type="text/javascript">
		$(document).ready(function(){
			$("#id_username, #id_password").addClass("form-control");
			$("#id_username").attr("placeholder", "Usuario");
			$("#id_password").attr("placeholder", "Contraseña");
		});
	</script>
{% endblock %} 

admin/templates/logout.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% block topmenu %}{% endblock %}

{% block mainbody %}

	<div class="jumbotron" style="padding-top:100px; height:100%; margin-bottom:0; position:absolute; top:0; bottom:0;left:0; right:0; text-align">
    	<div class="row">
    		<div class="col-xs-1 col-sm-2 col-md-2"></div>
    		<div class="col-xs-10 col-sm-8 col-md-8">
    			<div style="text-align:center">
    				<img alt="imagen no disponible" src="https://fbcdn-sphotos-f-a.akamaihd.net/hphotos-ak-ash3/t1.0-9/734113_389386964485689_331498768_n.jpg" 
		    			 alt="Periódico El Diario" class="img-rounded" width="100">
					<h1>Periódico El Diario</h1>
					<p>Administrador web</p>
		      		<small>Gracias por hacer de nuestro sitio algo cada vez mejor</small>
		      		<h3><a href="{% url 'login' %}">Iniciar sesión nuevamente</a></h3>
    			</div>
    		</div>
      	</div>
    </div>
{% endblock %} 

admin/templates/permission_err.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% block topmenu %}{% endblock %}

{% block mainbody %}

	<div class="jumbotron" style="padding-top:100px; height:100%; margin-bottom:0; position:absolute; top:0; bottom:0;left:0; right:0; text-align">
    	<div class="row">
    		<div class="col-xs-1 col-sm-2 col-md-2"></div>
    		<div class="col-xs-10 col-sm-8 col-md-8">
    			<div style="text-align:center">
    				<img alt="imagen no disponible" src="https://fbcdn-sphotos-f-a.akamaihd.net/hphotos-ak-ash3/t1.0-9/734113_389386964485689_331498768_n.jpg" 
		    			 alt="Periódico El Diario" class="img-rounded" width="100">
					<h1>Periódico El Diario</h1>
					<p>Administrador web</p>
                    <p>Permisos insuficientes</p>
		      		<small>Al parecer no tienes permisos suficientes para realizar esta acción</small>
		      		<h3><a href="/backend/">Volver al inicio</a></h3>
    			</div>
    		</div>
      	</div>
    </div>
{% endblock %} 

admin/templates/set_password.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}
{% block title %} Cambiar contraseña {% endblock %}

{% block breadcrumbs %}
	<ul class="breadcrumb">
		<li><a href="/backend"><i class="fa fa-home"></i> Inicio</a></li>
		<li><i class="fa fa-user"></i> {{user.username}}</li>
		<li>
			<i class="fa fa-key"></i> 
			Cambiar contraseña
		</li>
	</ul>
{% endblock %}

{% block mainbody %}
	<div id="content-main">
		<div class="row">
			<div class="col-xs-12 col-sm-10 col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
				    	<h2 class="panel-title"> 
				    		<span class="fa fa-key"></span> Cambiar tu contraseña
				    	</h2>
				  	</div>
				  	<div class="panel-body">
				  		<div class="row">
				  			<div class="col-md-1"></div>
				  			<div class="col-xs-12 col-md-10">
				  				{% if editing and not editing_pass%} 
				  					<p class="text-right">
				  						<a href="cambiar_password" class="btn btn-primary" style="width:25%;">
				  							<span class="fa fa-lock"></span> Cambiar contraseña
				  						</a>
				  					</p>
				  				{% endif %}
				  				<form role="form" action="." method="POST">
									{% csrf_token %}

									<input type="hidden" name="user_id" value="{{user}}" />
									
									{% for field in form %}

										
											<div class="form-group {% if field.errors %} has-error{% endif %}">

												{% if not form.this_is_the_login_form.errors %}

													{% if field.name != "password"%}
														<label class="control-label required" for="{{field.field.id}}">
															{{field.label}}:
														</label>
													{% endif %}
												{% endif %}

												{% if field.errors %}
													<span class="help-inline text-danger">
														{{field.errors}}
													</span>
												{% endif %}
												<div class="input-group">
													<span class="input-group-addon">
														<span class="glyphicon glyphicon-asterisk"></span>
													</span>
													
													{{ field }}
												
												</div>
											</div>
									{% endfor %}

									<br><br>
									<div class="form-group" style="text-align:right;">
										<a href="../" class="btn btn-danger">
											Cancelar
										</a>
										<button type="submit" class="btn btn-success"> 
											Cambiar contraseña
				    					</button>
									</div>	
								</form>
				  			</div>
				  		</div>
				  	</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

admin/templates/topmenu.html
{% load url from future %}
{% load static %}
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/backend">
				<img alt="imagen no disponible" src="{% static "images/home.png" %}" style="margin: 0 10px 4px 0;">
				Perdiódico El Diario
			</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

			<ul class="nav navbar-nav navbar-right">
				<li>
					<a href="/backend/suscripciones/">
						<i class="glyphicon glyphicon-send"></i> Nuevas suscipciones <span class="badge">{{new_susc}}</span>
					</a>
				</li>
				<li>
					<form class="navbar-form navbar-left" role="search">
						<div class="form-group">
							<input type="text" class="form-control" placeholder="Buscar">
						</div>
						<button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
					</form>
				</li>
				<li>
					<a href="/" target="_blank">
						<i class="glyphicon glyphicon-fullscreen"></i> Ver Frontend
					</a>
				</li>
				<li class="dropdown">
					<a data-toggle="dropdown" class="dropdown-toggle" href="#">
							<i class="glyphicon glyphicon-user"></i>&#xa0;
							{% filter force_escape %}
								{{user}}
							{% endfilter %}
							<b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							{% block userlinks %}

							{%comment%}
								{% if analytics %}
								<li>
									<a href="{% url 'admin:analytics' %}">
										<span class="glyphicon glyphicon-stats"></span>
										Configurar Google Analytics
									</a>
								</li>
								<li class="divider"></li>
								{% endif %}
							{% endcomment %}
								<li>
									<a href="/backend/ayuda">
										<span class="glyphicon glyphicon-book"></span>
										Documentación
									</a>
								</li>

								<li>
									<a href="/backend/nuevo_password/">
										<span class="glyphicon glyphicon-lock"></span>
										Cambiar contraseña
									</a>
								</li>


								{% url 'logout' as logout_url %}
								<li>
									<a href="{% if logout_url %}{{ logout_url }}{% else %}{{ homeurl }}logout/{% endif %}">
										<span class="glyphicon glyphicon-eject"></span>
										Cerrar sesión
									</a>
								</li>

							{% endblock %}
						</ul>
				</li>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>