ElDiario/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import static
from django.conf import settings

urlpatterns = patterns('',
    url(r'^', include('frontend.urls')),
    url(r'^backend', include('admin.urls')),
    url(r'^m/', include('mobile.urls')),
    url(r'^redactor/', include('redactor.urls')),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    url(r'session_security/', include('session_security.urls')),
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ads/urls.py
from django.conf.urls import patterns, url, include

urlpatterns = patterns('',
	url(r'^/$', 'ads.views.home', name='home'),
    url(r'^/nueva/', 'ads.views.add_ad', name='new_add'),
	url(r'^/editar/(?P<id>\d+)/$', 'ads.views.edit_ad', name='edit_ad'),
	url(r'^/publicar/$', 'ads.views.publish_group', name='publish_group'),
	url(r'^/despublicar/$', 'ads.views.unpublish_group', name='unpublish_group'),
	url(r'^/publicar/(?P<id>\d+)/$', 'ads.views.toggle_publish', name='toggle_publish'),
	url(r'^/despublicar/(?P<id>\d+)/$', 'ads.views.toggle_publish', name='toggle_publish'),
	url(r'^/eliminar/$', 'ads.views.delete_ad', name='delete_ad'),
)

photogallery/urls.py
from django.conf.urls import patterns, url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
	url(r'^/$', 'photogallery.views.home', name='home'),
    url(r'^/nueva/', 'photogallery.views.add_gallery', name='new_gallery'),
	url(r'^/editar/(?P<id>\d+)/$', 'photogallery.views.edit_gallery', name='edit_gallery'),
	url(r'^/publicar/$', 'photogallery.views.publish_group', name='publish_group'),
	url(r'^/despublicar/$', 'photogallery.views.unpublish_group', name='unpublish_group'),
	url(r'^/publicar/(?P<id>\d+)/$', 'photogallery.views.toggle_publish', name='toggle_publish'),
	url(r'^/despublicar/(?P<id>\d+)/$', 'photogallery.views.toggle_publish', name='toggle_publish'),
	url(r'^/eliminar/$', 'photogallery.views.delete_gallery', name='delete_gallery'),
	url(r'^/upload/$', 'photogallery.views.upload'),
	url(r'^/get_preview/$', 'photogallery.views.get_preview'),
	url(r'^/edit_image/(?P<id>\d+)/$', 'photogallery.views.edit_image'),
	url(r'^/imagenes/$', 'photogallery.views.index_images'),
	url(r'^/imagenes/nueva/$', 'photogallery.views.new_image'),
	url(r'^/imagenes/editar/(?P<id>\d+)/$', 'photogallery.views.edit_image'),
	url(r'^/imagenes/eliminar/$', 'photogallery.views.delete_image'), 
)

session_security/urls.py
"""
One url meant to be used by JavaScript.

session_security_ping
    Connects the PingView.

To install this url, include it in ``urlpatterns`` definition in ``urls.py``,
ie::

    urlpatterns = patterns('',
        # ....
        url(r'session_security/', include('session_security.urls')),
        # ....
    )

"""
try:
    from django.conf.urls import url, patterns
except ImportError:
    from django.conf.urls.defaults import url, patterns

from .views import PingView

urlpatterns = patterns('',
    url(
        'ping/$',
        PingView.as_view(),
        name='session_security_ping',
    ),
)

photogallery/models.py
#encoding: utf-8
from django.db import models
from django.contrib.auth.models import User
from content.models import Category, Article
from redactor.fields import RedactorField
from django.template.defaultfilters import slugify
# Create your models here.

media_types = (
	('i','Imagen'),
	('u','URL'),
	('v','Video')
)

class Gallery(models.Model):
	slug = models.SlugField(unique=True, blank=True, max_length=150)
	title = models.CharField(verbose_name=u'Título', max_length=100, unique=True)
	description = RedactorField(verbose_name=u'Descripción', blank=True)
	creation_date = models.DateTimeField(verbose_name=u'Fecha de creación')
	published = models.BooleanField(verbose_name=u'Publicada', default=True)
	author = models.ForeignKey(User, verbose_name=u'Autor')
	category = models.ForeignKey(Category, verbose_name=u'Categoría', null=True, blank=True)
	hits = models.IntegerField(default=0)
	images = models.ManyToManyField('Image', related_name='gallery', null=True, blank=True)
	article_related = models.ManyToManyField(Article, verbose_name=u'Artículos Relacionados', blank=True, null=True)

	def save(self, *args, **kwargs):
		self.slug = slugify(self.title)
		super(Gallery, self).save(*args, **kwargs)

class Image(models.Model):
	image_title = models.CharField(verbose_name=u'Título', max_length=100)
	media_type = models.CharField(verbose_name=u'Tipo', choices=media_types, max_length=5)
	image = models.ImageField(verbose_name=u'Archivo de Imagen', upload_to='uploads/galleries',blank=True, null=True)
	url = models.URLField(default='', blank=True, null=True, verbose_name=u'URL')
	code = models.TextField(verbose_name=u'Código Embebido', default='', blank=True, null=True)
	description = models.TextField(verbose_name=u'Descripción', blank=True)
	author = models.CharField(verbose_name=u'Fotógrafo', max_length=100, blank=True)
	capture_datetime = models.DateTimeField(verbose_name='Fecha de captura')

	def __unicode__(self):
			return self.image_title

photogallery/forms.py
#encoding: utf-8
from django import forms
from django.forms import ModelForm
from models import *


class GalleryForm(ModelForm):

	class Meta:
		model = Gallery
		exclude = ('hits','slug')

class ImageForm(ModelForm):

	class Meta:
		model = Image

		widgets = {
			'media_type': forms.RadioSelect(choices=media_types)
		}

photogallery/views.py
#encoding: utf-8
from django.shortcuts import render_to_response, HttpResponseRedirect, redirect
from django.template import RequestContext
from models import *
from forms import *

from django.contrib.auth.decorators import permission_required, login_required
# Create your views here.

TEMPLATE_DIR = 'photogallery/../'

def home(request):
	galleries = Gallery.objects.all()
	for gallery in galleries:
		images = gallery.images.all().count()
		gallery.images_count = images

	return render_to_response(TEMPLATE_DIR+'index_gallery.html', {'galleries':galleries},
								context_instance=RequestContext(request))

@login_required(login_url='login')
@permission_required('photogallery.add_gallery', login_url='/backend/permisos_insuficientes/')

def add_gallery(request):

	if request.method == 'GET':
		form = GalleryForm()
		image_form = ImageForm()
		available_images = Image.objects.all()

		return render_to_response(TEMPLATE_DIR+'add_edit_gallery.html',
							  {'form':form, 'image_form':image_form, 'available_images':available_images},
							  context_instance=RequestContext(request))

	elif request.method == 'POST':
		form = GalleryForm(request.POST)
		if form.is_valid():
			new_galery = form.save()
			return HttpResponseRedirect('/backend/fotogalerias/editar/'+str(new_galery.id))
		else:
			return render_to_response(TEMPLATE_DIR+'add_edit_gallery.html',
					  {'form':form}, context_instance=RequestContext(request))

@login_required(login_url='login')
@permission_required('photogallery.change_gallery', login_url='/backend/permisos_insuficientes/')
def edit_gallery(request, id):

	gallery = Gallery.objects.get(id=id)

	if request.method == 'GET':
		image_form = ImageForm()
		form = GalleryForm(instance=gallery)
		gallery_images = gallery.images.all()
		available_images = Image.objects.exclude(gallery=gallery)


		return render_to_response(TEMPLATE_DIR+'add_edit_gallery.html',
							  {'form':form, 'editing':True, 'title':gallery.title,
							   'image_form': image_form, 'g_images':gallery_images,
							   'available_images': available_images},
							  context_instance=RequestContext(request))

	elif request.method == 'POST':
		form = GalleryForm(request.POST, instance=gallery)
        if form.is_valid():
            new_gallery = form.save()
            return HttpResponseRedirect('/backend/fotogalerias')
        else:
        	return render_to_response(TEMPLATE_DIR+'add_edit_gallery.html',
							  {'form':form, 'editing':True, 'title':gallery.title}, context_instance=RequestContext(request))

@login_required(login_url='login')
@permission_required('photogallery.change_gallery', login_url='/backend/permisos_insuficientes/')
def publish_group(request):
	ids = request.POST.getlist('id')
	for gallery_id in ids:
		gallery = Gallery.objects.get(id=int(gallery_id))
		gallery.published = True
		gallery.save()
	return HttpResponseRedirect('/backend/fotogalerias')

@login_required(login_url='login')
@permission_required('photogallery.change_gallery', login_url='/backend/permisos_insuficientes/')
def unpublish_group(request):
	ids = request.POST.getlist('id')
	for gallery_id in ids:
		gallery = Gallery.objects.get(id=int(gallery_id))
		gallery.published = False
		gallery.save()
	return HttpResponseRedirect('/backend/fotogalerias')

@login_required(login_url='login')
@permission_required('photogallery.change_gallery', login_url='/backend/permisos_insuficientes/')
def toggle_publish(request, id):
	gallery = Gallery.objects.get(id=id)
	gallery.published = not gallery.published
	gallery.save()
	return HttpResponseRedirect('/backend/fotogalerias')


@login_required(login_url='login')
@permission_required('photogallery.delete_gallery', login_url='/backend/permisos_insuficientes/')
def delete_gallery(request):
	ids = request.POST.getlist('id')
	for gallery_id in ids:

		print 'x', gallery_id

		gallery = Gallery.objects.get(id=int(gallery_id))
		gallery.delete()
	return HttpResponseRedirect('/backend/fotogalerias')



import json
from django.http import HttpResponse



def upload(request):
	response_data = {}

	if request.method == 'GET':
		form = ImageForm()
		return render_to_response(TEMPLATE_DIR+'upload_test.html',
							  {'form':form}, context_instance=RequestContext(request))

	if request.method=='POST':    #.is_ajax():

		form = ImageForm(request.POST, request.FILES)

		if form.is_valid():

			upload = None
			Image(
				image=None
			)

			if request.FILES:
				upload = Image(
					image=request.FILES['image']
				)
			else:
				upload = Image(
					image=None
				)

			upload.image_title = request.POST.get('image_title')
			upload.url = request.POST.get('url')
			upload.code = request.POST.get('code')
			upload.author = request.POST.get('author')
			upload.description = request.POST.get('description')

			upload.save()

			images = Image.objects.all()

			return render_to_response(TEMPLATE_DIR+'browse.html',
						{'available_images':images}, context_instance=RequestContext(request))
		else:
			print form.errors
			return HttpResponse("error")


	response_data['status'] = "error"
	response_data['result'] = "We're sorry, but something went wrong. Please be sure that your file respects the upload conditions."

	return HttpResponse(json.dumps(response_data), content_type='application/json')



def get_preview(request):
	image_ids = request.GET.getlist('images')

	images = []

	for id in image_ids:
		images.append(Image.objects.get(id=int(id)))

	order = range(0,len(images))

	print order

	return render_to_response(TEMPLATE_DIR+'carrousel.html',
				{'images':images, 'title':'jejeje', 'order':order}, context_instance=RequestContext(request))


def index_images(request):
	images = Image.objects.all()

	return render_to_response(TEMPLATE_DIR+'index_images.html', {'images':images},
								context_instance=RequestContext(request))

@login_required(login_url='login')
@permission_required('photogallery.add_image', login_url='/backend/permisos_insuficientes/')
def new_image(request):
	if request.method == 'GET':
		form = ImageForm()
		return render_to_response(TEMPLATE_DIR+'add_edit_image.html',
								{'form':form}, context_instance=RequestContext(request))

	if request.method=='POST':

		form = ImageForm(request.POST, request.FILES)

		if form.is_valid():

			form.save()

			return redirect('/backend/fotogalerias/imagenes')
		else:
			return render_to_response(TEMPLATE_DIR+'add_edit_image.html',
									{'form':form}, context_instance=RequestContext(request))

@login_required(login_url='login')
@permission_required('photogallery.change_image', login_url='/backend/permisos_insuficientes/')
def edit_image(request, id):
	if request.method == 'GET':
		image = Image.objects.get(id=id)
		form = ImageForm(instance=image)
		return render_to_response(TEMPLATE_DIR+'add_edit_image.html',
								{'form':form, 'editing':True, 'title':image.image_title}, context_instance=RequestContext(request))

	if request.method=='POST':
		image = Image.objects.get(id=id)
		form = ImageForm(request.POST, request.FILES, instance=image)

		if form.is_valid():

			form.save()

			return redirect('/backend/fotogalerias/imagenes')
		else:
			return render_to_response(TEMPLATE_DIR+'add_edit_image.html',
									{'form':form, 'editing':True, 'title':image.image_title}, context_instance=RequestContext(request))

@login_required(login_url='login')
@permission_required('photogallery.delete_image', login_url='/backend/permisos_insuficientes/')
def delete_image(request):
	ids = request.POST.getlist('id')
	for image_id in ids:
		image = Image.objects.get(id=int(image_id))
		image.delete()
	return HttpResponseRedirect('/backend/fotogalerias/imagenes')

photogallery/templates/add_edit_gallery.html
{% extends "base.html" %}
{% load static i18n %}
{% load url from future %}
{% block title %} {% if editing %} Editando la galería: {{title}} {% else %} Nueva Galería {% endif %} {% endblock %}

{% block extrastyle %}
		<link rel="stylesheet" href="{% static "css/chosen.min.css"%}"></link>
{% endblock %}

{% block extrahead %}
	<script src="{% static "js/chosen.jquery.min.js"%}"></script>
	<script src="{% static "js/jquery.form.js"%}"></script>
{% endblock %}

{% block breadcrumbs %}
	<ul class="breadcrumb">
		<li><a href="/backend"><i class="fa fa-home"></i> Inicio</a></li>
		<li><a href="/backend/fotogalerias"><i class="fa fa-camera"></i> Galerías</a></li>
		<li>
			<i class="{% if editing %}fa fa-edit {% else %}fa fa-plus {% endif %}"></i>
			{% if editing %} Editar Galería ({{title}}) {% else %} Nueva Galería {% endif %}
		</li>
	</ul>
{% endblock %}

{% block mainbody %}
	<div id="content-main">
		<div class="row">
			<div class="col-xs-12 col-sm-10 col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
				    	<h2 class="panel-title">
				    		{% if editing %} <span class="fa fa-edit"></span> Editar Galería ({{title}})
				    		{% else %} <span class="fa fa-plus"></span> Nueva Galería  {% endif %}

				    	</h2>
				  	</div>
				  	<div class="panel-body">
				  		<div class="row">
				  			<div class="col-md-1 hidden-xs" style="width:4%;"></div>
				  			<div class="col-xs-12 col-md-6">
				  				<form role="form" action="." method="POST">
									{% csrf_token %}

									<input type="hidden" name="user_id" value="{{user}}" />

									{% for field in form %}

										<div class="form-group {% if field.errors %} has-error{% endif %}">
											{% if not form.this_is_the_login_form.errors %}
												{% if field.name != "images" %}
												<label class="control-label required" for="{{field.field.id}}">
													{{field.label}}:
												</label>
												{% endif %}
											{% endif %}

											{% if field.errors %}
												<span class="help-inline text-danger">
													{{field.errors}}
												</span>
											{% endif %}

											{% if field.name != "images" %}
											<div class="input-group">
											{% else %}
											<div class="input-group">
											{% endif %}
												<span class="input-group-addon">
													<span class="glyphicon glyphicon-asterisk"></span>
												</span>
												{{ field }}
											</div>
										</div>
									{% endfor %}

									<br><br>
									<div class="form-group" style="text-align:right;">
										<a href="{% if editing %}../../{% else %}../{% endif %}" class="btn btn-danger">
											Cancelar
										</a>
										<button type="submit" class="btn btn-success">
											{% if editing %} Guardar cambios
				    						{% else %} Crear Galería {% endif %}
				    					</button>
									</div>
								</form>
				  			</div>
								{% if editing %}
				  			<div class="col-xs-12 col-md-5">
				  				<div class="panel panel-default">
								  <div class="panel-body">
								    <h3 style="display:inline-block; margin-right: 20px;">
								    	<span class="glyphicon glyphicon-picture">
								    	</span> Imágenes de la galería
								    </h3>
							    	<div class="btn-group" style="display:inline-block">
										<button type="button" class="btn btn-default" data-toggle="modal" data-target=".bs-example-modal-lg">
											<span class="fa fa-plus"></span> Nueva
										</button>
										<button type="button" id="drop_img" class="btn btn-default delete disabled">
											<span class="glyphicon glyphicon-fire"></span> Eliminar
										</button>
										<button type="button" class="btn btn-default preview">
											<span class="glyphicon glyphicon-fullscreen"></span> Vista
										</button>
									</div>
									<hr style="margin-bottom:0;">
									<div class="text-center">

										<table id="current_images" class="table table-striped" style="margin-bottom:0;">
									      <thead>
									        <tr class="active">
									        	<th class="text-center"><input type="checkbox" id="toggle_all"/></th>
									        	<th class="text-left" class="hidden-xs">Imagen</th>
									        	<th class="text-left">Título</th>
									        	<th class="text-center" class="hidden-xs">Fotógtrafo</th>
														<th class="text-center" class="hidden-xs">Fecha</th>
														<th class="text-center" class="hidden-xs">Descr.</th>
									        </tr>
									      </thead>
									      <tbody>

									      	{% for g_image in g_images %}
									        <tr>
									        	<td class="text-left">
									        		<input type="checkbox" class="check" name="id" form="all_objects" value="{{g_image.id}}"/>
									        	</td>
									        	<td class="text-left">
									        		<a href="#" attr-id="{{g_image.id}}">
																{% if g_image.code%}
																	<span class="fa fa-video-camera video" data-embed="{{ g_image.code }}"></span> Ver Video
																{% else %}
									        			<img class="img-thumbnail"
																	{%if g_image.image%}src="/media/{{g_image.image}}"
																	{%else%}src="{{g_image.url}}"{%endif%}>
																{% endif %}
									        		</a>
									        	</td>
									        	<td class="text-left">{{g_image.image_title}}</td>
									        	<td class="text-center">{{g_image.author}}</td>
									        	<td class="text-left">{{g_image.capture_datetime|date:"d \d\e M \d\e\l Y"}}</td>
									        	<td class="text-left">{{g_image.description}}</td>
									        </tr>
									        {% empty %}
									        <tr class="empty-mess">
									        	<td colspan="6">
									        		<div class="alert alert-info">
														No has agregado imágenes a esta galería <br>
														<a href="" data-toggle="modal" data-target=".bs-example-modal-lg">
															<b><span class="fa fa-plus">
															</span> Agregar una imagen</b>
														</a>
													</div>
									        	</td>
									        </tr>
									        {% endfor %}
									      </tbody>
									    </table>
									</div>
								    <hr style="margin-top:0;">
								  </div>
								</div>
				  			{%endif%}
								</div>
				  		</div>
				  	</div>
				</div>
			</div>
		</div>
	</div>

<div class="modal fade" id="carousel-prev-modal" tabindex="-1" role="dialog" aria-labelledby="CarouselPrev" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="CarouselPrev">Vista previa Fotogalería: {{title}}</h4>
			</div>
			<div class="modal-body carousel-full">
				{% include 'carrousel.html'%}
			</div>

			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
			</div>
		</div>
	</div>
</div>

	{% include 'img_preview.html'%}

	{% include 'picmanager.html' %}

	<script>
        var message = '';
        var options = {
            url: '/backend/fotogalerias/upload/',
            error: function(response) {
            	alert("Error de subida "+response.result)
                message = '<span class="error">We\'re sorry, but something went wrong. Retry.</span>';
                $('.upload-message').html(message);
                $('fileInput').val('');
            },
            success: function(response) {
                $("#uploadForm input:not(input[type=hidden]), #uploadForm textarea").val('');
                $("#choose").html(response);
								$('#image_tabs a:first').tab('show');

								$("#id_images").html("");
								$("#choose .img-thumbnail").each(function(){
									alert($(this).attr("img_id"));
									$("#id_images").append('<option value="'+$(this).attr("img_id")+'" id="img_'+$(this).attr("img_id")+'">'+$(this).attr("img_title")+'</option>');
								});
								$(".empty-msg").detach();
            }
        };

        $("#send_form").click(function(event){
        	event.preventDefault();
        	$('#uploadForm').ajaxSubmit(options);
        });

        $("#choose").on("click",".img-thumbnail", function(){
					if($(this).hasClass("selected")){
							$(this).removeClass("selected");
					}else{
							$(this).addClass("selected");
					}

        	$("#img_"+$(this).attr('img_id')).attr('selected', true);
        });

				$('#confirm_images').click(function(){

					if($('#choose .selected').length>0){$(".empty-mess").hide();}

					$('#choose .selected').each(function(){
						if($(this).hasClass("video_thumb")){
							$("#current_images tbody").append(
								'<tr>\
									<td class="text-left">\
										<input type="checkbox" class="check" name="id" form="all_objects" value="'+$(this).attr('img_id')+'"/>\
									</td>\
									<td class="text-left">\
										<a href="#"><span class="fa fa-video-camera"></span> Ver video</a>\
									</td>\
									<td class="text-left">'+$(this).attr('img_title')+'</td>\
									<td class="text-center">'+$(this).attr('img_author')+'</td>\
									<td class="text-left">'+$(this).attr('img_date')+'</td>\
									<td class="text-left">'+$(this).attr('img_description')+'</td>\
								</tr>'
							);
						}else{
								$("#current_images tbody").append(
									'<tr>\
										<td class="text-left">\
											<input type="checkbox" class="check" name="id" form="all_objects" value="'+$(this).attr('img_id')+'"/>\
										</td>\
										<td class="text-left">\
											<a href="#"><img class="img-thumbnail" src="'+$(this).attr('src')+'"></a>\
										</td>\
										<td class="text-left">'+$(this).attr('img_title')+'</td>\
										<td class="text-center">'+$(this).attr('img_author')+'</td>\
										<td class="text-left">'+$(this).attr('img_date')+'</td>\
										<td class="text-left">'+$(this).attr('img_description')+'</td>\
									</tr>'
								);
						}

						$(this).detach();

						$(".bs-example-modal-lg").modal('hide')
					});
				});

        $(document).ready(function(){

					$("#id_images").hide();

        	$("#id_images option").each(function(){
        		$(this).attr('id', 'img_'+$(this).attr('value'));
        	});

        	$("#drop_img").click(function(){
        		$(".check:checked").each(function(){
        			$("#img_"+$(this).val()).attr('selected', false);
        			$(this).parent().parent().remove();
        		});
        	});

        	$("#current_images").delegate("tr td a", "click", function(){

        		//$('.image-prev-modal').modal('show');

						$.ajax({
							url: '/backend/fotogalerias/edit_image/'+$(this).attr('attr-id'),

							success: function(response){
								alert(response);

								$(".image-prev-modal").html(response);
								clear_fields();
								$(".image-prev-modal").modal('show');
							},
						});
        	});

        	$(".preview").click(function(){

        		$.ajax({
						  url: '/backend/fotogalerias/get_preview/',

						  data: $("#id_images").serialize(),

						  success: function(response){
								$(".carousel-full").html(response);
								$("#carousel-prev-modal").modal('show');
							},
						});
        	});

        });

				$("#id_article_related").chosen({placeholder_text_multiple:'Escribe para buscar...',width: "100%"});
    </script>

{% endblock %}

photogallery/templates/browse.html
<div class="container">
  <div class="col-md-8">

    <div style="margin-bottom:20px;">
        <h3 style="display:inline-block">Seleccionar imágenes existentes</h3>
        <a style="display:inline:block; margin-left:30%;" href="/backend/fotogalerias/imagenes/" class="btn btn-primary">
          <span class="glyphicon glyphicon-picture"></span>
          Administrar Imágenes
        </a>
    </div>


    <div class="well pic_manager">
      {% for av_img in available_images %}
        {% if av_img.code %}
          <div img_id="{{av_img.id}}" img_title="{{av_img.image_title}}"
          img_author="{{av_img.author}}" img_description="{{av_img.description}}"
          img_date="{{av_img.capture_datetime|date:"d \d\e M \d\e\l Y"}}"
          img_id="{{av_img.id}}" class="video_thumb img-thumbnail text-center">
              {{ av_img.code|safe }}
              <span class="fa fa-plus"></span> Agregar
          </div>

        {% else %}
          <img class="img-thumbnail" img_id="{{av_img.id}}" img_title="{{av_img.image_title}}"
          img_author="{{av_img.author}}" img_description="{{av_img.description}}"
          img_date="{{av_img.capture_datetime|date:"d \d\e M \d\e\l Y"}}"
          {% if av_img.url %}src="{{av_img.url}}"{% else %}src="/media/{{av_img.image}}"{%endif%}/>
        {% endif%}
      {% empty %}
      <span class="empty-msg">No has subido imágenes</span>
      {% endfor %}
    </div>

  </div>

photogallery/templates/picmanager.html
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog"
aria-labelledby="PicManager" aria-hidden="true">

	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="PicManager">
					Agregar imágenes a la galería ({% if editing %}{{title}}{% else %}Nueva Galería{%endif%})
				</h4>
			</div>

			<div class="modal-body">
				<ul class="nav nav-tabs" id="image_tabs">
					<li class="active"><a href="#choose" data-toggle="tab">Elegir imágenes</a></li>
				</ul>

					<div class="tab-content">
						<div class="tab-pane fade in active" id="choose">
							{% include "browse.html"%}
						</div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<button type="button" id="confirm_images" class="btn btn-primary">Guardar cambios</button>
			</div>
		</div>
	</div>

</div>

<script type="text/javascript">
	$(document).ready(function(){
		clear_fields();
	});
	var clear_fields = function(){
		$("#id_media_type li:first").detach()

		$("#id_media_type li :radio:first").attr("checked", "checked");
		$("#id_url, #id_code").parents(".form-group").hide();
		//alert($("input[name=ad_type][value=1]").("color"))
		$("#id_media_type").siblings(".input-group-addon").detach()

		$("#id_media_type li :radio").change(function(){
			if($(this).val()=='i'){
				$("#id_url, #id_code").parents(".form-group").fadeOut(function(){
					$("#id_image").parents(".form-group").slideDown();
				});

			}else if($(this).val()=='u'){
				$("#id_image, #id_code").parents(".form-group").fadeOut(function(){
					$("#id_url").parents(".form-group").slideDown();
				});

			}else{
				$("#id_image, #id_url").parents(".form-group").fadeOut(function(){
					$("#id_code").parents(".form-group").slideDown();
				});
			}
		})
	}
</script>